### ISSUE TITLE
Missing Placeholders

### ISSUE THREAD

**Issue by ksdme** [IOSD/RegitrationPortalSynergy2#2]
I am not really sure if this is the place you would like me to report an issue with your registration form but here is what I found anyway, I was at the HackDTU page to register and all the Text Input placeholders were missing on the form when I tried it on Firefox 55.0.2 64 Bit build, Also I haven't really tested it out on any other browser, So I am not sure if it is a persistent issue.
![image](https://user-images.githubusercontent.com/12156014/30525516-b3230bf0-9c25-11e7-87bb-3bbbc4d09015.png)

**Comment by ksdme** [comment]
Now that I see it, The Code In Less page is missing those placeholders too.

**Comment by krishnarai30** [comment]
@ksdme Hi, for now, the registration form doesn't support Firefox or Internet Explorer.
Also, this is not the code being used for registration we didn't push in the final version in this repository.
